setting: "Function correctness"

baseline:
  name: "RL baseline"
  accuracy_path: "results/reasoner_accuracy_summary.json"
  monitors:
    - name: "gpt-4o-mini"
      accuracy_path: "results/gpt-4o-mini_monitor_predictions_summary.json"
    - name: "gpt-4o"
      accuracy_path: "results/gpt-4o_monitor_predictions_summary.json"

runs:
  - name: "Penalise verbosity"
    accuracy_path: "results/reasoner_accuracy_summary.json"
    monitors:
      - name: "gpt-4o-mini"
        accuracy_path: "results/gpt-4o-mini_monitor_predictions_summary.json"
      - name: "gpt-4o"
        accuracy_path: "results/gpt-4o_monitor_predictions_summary.json"

  - name: "Reward verbosity"
    accuracy_path: "results/reasoner_accuracy_summary.json"
    monitors:
      - name: "gpt-4o-mini"
        accuracy_path: "results/gpt-4o-mini_monitor_predictions_summary.json"
      - name: "gpt-4o"
        accuracy_path: "results/gpt-4o_monitor_predictions_summary.json"



  - name: "Penalise KL"
    accuracy_path: "results/reasoner_accuracy_summary.json"
    monitors:
      - name: "gpt-4o-mini"
        accuracy_path: "results/gpt-4o-mini_monitor_predictions_summary.json"
      - name: "gpt-4o"
        accuracy_path: "results/gpt-4o_monitor_predictions_summary.json"


  - name: "Reward KL"
    accuracy_path: "results/reasoner_accuracy_summary.json"
    monitors:
      - name: "gpt-4o-mini"
        accuracy_path: "results/gpt-4o-mini_monitor_predictions_summary.json"
      - name: "gpt-4o"
        accuracy_path: "results/gpt-4o_monitor_predictions_summary.json"

  - name: "Penalise monitorability"
    accuracy_path: "results/reasoner_accuracy_summary.json"
    monitors:
      - name: "gpt-4o-mini"
        accuracy_path: "results/gpt-4o-mini_monitor_predictions_summary.json"
      - name: "gpt-4o"
        accuracy_path: "results/gpt-4o_monitor_predictions_summary.json"

  - name: "Reward monitorability"
    accuracy_path: "results/reasoner_accuracy_summary.json"
    monitors:
      - name: "gpt-4o-mini"
        accuracy_path: "results/gpt-4o-mini_monitor_predictions_summary.json"
      - name: "gpt-4o"
        accuracy_path: "results/gpt-4o_monitor_predictions_summary.json"



