setting: "Diamond in a vault"

baseline:
  name: "RL baseline"
  accuracy_path: "results/regular/predictions/reasoner_accuracy_summary.json"
  reasoner_predictions_path: "results/regular/predictions/global_step_460_predictions.json"
  monitors:
    - name: "gpt-4o-mini"
      accuracy_path: "results/regular/predictions/gpt_4o_mini_monitor_predictions_summary.json"
      predictions_path: "results/regular/predictions/gpt_4o_mini_monitor_predictions.json"
    - name: "gpt-4o"
      accuracy_path: "results/regular/predictions/gpt_4o_monitor_predictions_summary.json"
      predictions_path: "results/regular/predictions/gpt_4o_monitor_predictions.json"

runs:
  - name: "Penalise verbosity"
    accuracy_path: "results/penalize_verbosity_1e-7/s780/predictions/reasoner_accuracy_summary.json"
    reasoner_predictions_path: "results/penalize_verbosity_1e-7/s780/predictions/_predictions.json"
    monitors:
      - name: "gpt-4o-mini"
        accuracy_path: "results/penalize_verbosity_1e-7/s780/predictions/gpt_4o_mini_monitor_predictions_summary.json"
        predictions_path: "results/penalize_verbosity_1e-7/s780/predictions/gpt_4o_mini_monitor_predictions.json"
      - name: "gpt-4o"
        accuracy_path: "results/penalize_verbosity_1e-7/s780/predictions/gpt_4o_monitor_predictions_summary.json"
        predictions_path: "results/penalize_verbosity_1e-7/s780/predictions/gpt_4o_monitor_predictions.json"

  - name: "Reward verbosity"
    accuracy_path: "results/reward_verbosity_1e-9/s555/predictions/reasoner_accuracy_summary.json"
    reasoner_predictions_path: "results/reward_verbosity_1e-9/s555/predictions/_predictions.json"
    monitors:
      - name: "gpt-4o-mini"
        accuracy_path: "results/reward_verbosity_1e-9/s555/predictions/gpt_4o_mini_monitor_predictions_summary.json"
        predictions_path: "results/reward_verbosity_1e-9/s555/predictions/gpt_4o_mini_monitor_predictions.json"
      - name: "gpt-4o"
        accuracy_path: "results/reward_verbosity_1e-9/s555/predictions/gpt_4o_monitor_predictions_summary.json"
        predictions_path: "results/reward_verbosity_1e-9/s555/predictions/gpt_4o_monitor_predictions.json"

  - name: "Penalise KL"
    accuracy_path: "results/penalize_kl_1e-3/s520/predictions/reasoner_accuracy_summary.json"
    reasoner_predictions_path: "results/penalize_kl_1e-3/s520/predictions/_predictions.json"
    monitors:
      - name: "gpt-4o-mini"
        accuracy_path: "results/penalize_kl_1e-3/s520/predictions/gpt_4o_mini_monitor_predictions_summary.json"
        predictions_path: "results/penalize_kl_1e-3/s520/predictions/gpt_4o_mini_monitor_predictions.json"
      - name: "gpt-4o"
        accuracy_path: "results/penalize_kl_1e-3/s520/predictions/gpt_4o_monitor_predictions_summary.json"
        predictions_path: "results/penalize_kl_1e-3/s520/predictions/gpt_4o_monitor_predictions.json"

  - name: "Reward KL"
    accuracy_path: "results/reward_kl_1e-2/s470/predictions/reasoner_accuracy_summary.json"
    reasoner_predictions_path: "results/reward_kl_1e-2/s470/predictions/_predictions.json"
    monitors:
      - name: "gpt-4o-mini"
        accuracy_path: "results/reward_kl_1e-2/s470/predictions/gpt_4o_mini_monitor_predictions_summary.json"
        predictions_path: "results/reward_kl_1e-2/s470/predictions/gpt_4o_mini_monitor_predictions.json"
      - name: "gpt-4o"
        accuracy_path: "results/reward_kl_1e-2/s470/predictions/gpt_4o_monitor_predictions_summary.json"
        predictions_path: "results/reward_kl_1e-2/s470/predictions/gpt_4o_monitor_predictions.json"

  - name: "Penalise monitorability"
    accuracy_path: "results/training_against_monitor/s560/predictions/reasoner_accuracy_summary.json"
    reasoner_predictions_path: "results/training_against_monitor/s560/predictions/_predictions.json"
    monitors:
      - name: "gpt-4o-mini"
        accuracy_path: "results/training_against_monitor/s560/predictions/gpt_4o_mini_monitor_predictions_summary.json"
        predictions_path: "results/training_against_monitor/s560/predictions/gpt_4o_mini_monitor_predictions.json"
      - name: "gpt-4o"
        accuracy_path: "results/training_against_monitor/s560/predictions/gpt_4o_monitor_predictions_summary.json"
        predictions_path: "results/training_against_monitor/s560/predictions/gpt_4o_monitor_predictions.json"

  - name: "Reward monitorability"
    accuracy_path: "results/training_for_monitor/s560/predictions/reasoner_accuracy_summary.json"
    reasoner_predictions_path: "results/training_for_monitor/s560/predictions/_predictions.json"
    monitors:
      - name: "gpt-4o-mini"
        accuracy_path: "results/training_for_monitor/s560/predictions/gpt_4o_mini_monitor_predictions_summary.json"
        predictions_path: "results/training_for_monitor/s560/predictions/gpt_4o_mini_monitor_predictions.json"
      - name: "gpt-4o"
        accuracy_path: "results/training_for_monitor/s560/predictions/gpt_4o_monitor_predictions_summary.json"
        predictions_path: "results/training_for_monitor/s560/predictions/gpt_4o_monitor_predictions.json"